[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = false

# Uncomment to override default task
#[tasks.default]
#clear = true
#command = "cargo"
#args = ["build"]
#dependencies = ["build_dependencies"]

# Default task is build
[tasks.build]
args = ["build"]
dependencies = ["build_dependencies"]

[tasks.build_dependencies]
command = "git"
args = ["submodule", "update", "--init", "--recursive"]

[tasks.cli_simple]
env = { "RUST_LOG" = "debug" }
command = "cargo"
args = ["run", "--", "--hf-repo", "TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF", "--hf-file", "tinyllama-1.1b-chat-v1.0.Q2_K.gguf", "--ngl", "99", "-p", "You are a helpful assistant."]
dependencies = ["build_dependencies"]

[tasks.cli_code_suggestion]
env = { "RUST_LOG" = "debug" }
command = "cargo"
args = ["run", "--", "--hf-repo", "ggml-org/Qwen2.5-Coder-1.5B-Q8_0-GGUF", "--hf-file", "qwen2.5-coder-1.5b-q8_0.gguf", "--ngl", "99", "-p", "You are a helpful assistant."]
dependencies = ["build_dependencies"]
