[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

# Uncomment to override default task
#[tasks.default]
#clear = true
#command = "cargo"
#args = ["build"]
#dependencies = ["build_dependencies"]

# Default task is build
[tasks.build]
args = ["build"]
dependencies = ["build_dependencies"]

[tasks.build_dependencies]
command = "git"
args = ["submodule", "update", "--init", "--recursive"]

[tasks.lint]
dependencies = ["build_dependencies","lint_rust"]

[tasks.lint_rust]
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]
dependencies = ["build_dependencies"]

[tasks.cli_simple]
env = { "RUST_LOG" = "info" }
command = "cargo"
args = ["run", "--bin", "cli", "--", "--hf-repo", "ggml-org/gemma-1.1-2b-it-Q8_0-GGUF", "--hf-file", "gemma-1.1-2b-it.Q8_0.gguf", "--ngl", "99", "-p", "Tell me something I don't know"]
dependencies = ["build_dependencies"]

[tasks.cli_deepseek]
env = { "RUST_LOG" = "info" }
command = "cargo"
args = ["run", "--bin", "cli", "--", "--hf-repo", "ggml-org/DeepSeek-R1-Distill-Qwen-1.5B-Q4_0-GGUF", "--hf-file", "deepseek-r1-distill-qwen-1.5b-q4_0.gguf", "--ngl", "99", "-p", "Tell me something I don't know"]
dependencies = ["build_dependencies"]

[tasks.cli_tinyllama]
env = { "RUST_LOG" = "info" }
command = "cargo"
args = ["run", "--bin", "cli", "--", "--hf-repo", "TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF", "--hf-file", "tinyllama-1.1b-chat-v1.0.Q2_K.gguf", "--ngl", "99", "-p", "Tell me something I don't know"]
dependencies = ["build_dependencies"]

[tasks.cli_code_suggestion]
env = { "RUST_LOG" = "info" }
command = "cargo"
args = ["run", "--bin", "cli", "--", "--hf-repo", "ggml-org/Qwen2.5-Coder-0.5B-Q8_0-GGUF", "--hf-file", "qwen2.5-coder-0.5b-q8_0.gguf", "--ngl", "99", "-p", "Tell me something I don't know"]
dependencies = ["build_dependencies"]
