[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

# Uncomment to override default task
#[tasks.default]
#clear = true
#command = "cargo"
#args = ["build"]
#dependencies = ["build_dependencies"]

# Default task is build
[tasks.build]
args = ["build"]
dependencies = ["build_dependencies"]

[tasks.build_dependencies]
command = "git"
args = ["submodule", "update", "--recursive"]

# Fix some weird build issues with clang on MacOS
[tasks.reinstall_xcode_cli]
script = [
	"sudo rm -rf /Library/Developer/CommandLineTools",
	"sudo xcode-select --install",
	"sudo xcodebuild -license",
]

[tasks.lint]
dependencies = ["build_dependencies", "lint_rust"]

[tasks.lint_rust]
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]
dependencies = ["build_dependencies"]

[tasks.cli_simple]
env = { "RUST_LOG" = "info" }
command = "cargo"
args = [
	"run",
	"--bin",
	"cli",
	"--",
	"--hf-repo",
	"TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF",
	"--hf-file",
	"tinyllama-1.1b-chat-v1.0.Q2_K.gguf",
	"--ngl",
	"99",
	"-p",
	"What is the meaning of life? Please answer it short and concise.",
]
dependencies = ["build_dependencies"]

[tasks.llamacpp_simple]
command = "llama-run"
args = [
	"hf://TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/tinyllama-1.1b-chat-v1.0.Q2_K.gguf",
	"<<",
	"What is the meaning of life? Please answer it short and concise.",
]

[tasks.cli_deepseek]
env = { "RUST_LOG" = "info" }
command = "cargo"
args = [
	"run",
	"--bin",
	"cli",
	"--",
	"--hf-repo",
	"ggml-org/DeepSeek-R1-Distill-Qwen-1.5B-Q4_0-GGUF",
	"--hf-file",
	"deepseek-r1-distill-qwen-1.5b-q4_0.gguf",
	"--ngl",
	"99",
	"-p",
	"What is the meaning of life? Please answer it short and concise.",
]
dependencies = ["build_dependencies"]

[tasks.cli_code_suggestion]
env = { "RUST_LOG" = "info" }
command = "cargo"
args = [
	"run",
	"--bin",
	"cli",
	"--",
	"--hf-repo",
	"TheBloke/stable-code-3b-GGUF",
	"--hf-file",
	"stable-code-3b.Q4_K_M.gguf",
	"--ngl",
	"99",
	"-p",
	"Generate Rust snippet for axum-based protobuf server, keep it short and simple.",
]
dependencies = ["build_dependencies"]
